individuals:
  UDN052264:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00456/hg38/results/pipelines/k-mer-variant-phasing/results/PS00456/hiphase/PS00456.vcf.gz
    untreated:
        non-cyclo_PS00366: 
          - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00366/m84046_230829_213454_s3/MAS_3p--10X_IsoSeqX_bc16_5p/PS00366.m84046_230829_213454_s3.MAS_3p--10X_IsoSeqX_bc16_5p.flnc.bam
    treated:
        cyclo_PS00367:
          - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00367/m84046_230829_213454_s3/MAS_3p--10X_IsoSeqX_bc17_5p/PS00367.m84046_230829_213454_s3.MAS_3p--10X_IsoSeqX_bc17_5p.flnc.bam
  BCH_2410-01:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00392/hg38/results/pipelines/k-mer-variant-phasing/results/PS00392/hiphase/PS00392.vcf.gz
    treated:
        cyclo_PS00393:
          - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00393/m84046_231117_223025_s4/IsoSeqX_bc03_5p--IsoSeqX_3p/PS00393.m84046_231117_223025_s4.IsoSeqX_bc03_5p--IsoSeqX_3p.flnc.bam
          - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00393/m84046_231120_235038_s1/IsoSeqX_bc03_5p--IsoSeqX_3p/PS00393.m84046_231120_235038_s1.IsoSeqX_bc03_5p--IsoSeqX_3p.flnc.bam
    untreated:
        non-cyclo_PS00394: 
          - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00394/m84046_231117_223025_s4/IsoSeqX_bc04_5p--IsoSeqX_3p/PS00394.m84046_231117_223025_s4.IsoSeqX_bc04_5p--IsoSeqX_3p.flnc.bam
          - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00394/m84046_231120_235038_s1/IsoSeqX_bc04_5p--IsoSeqX_3p/PS00394.m84046_231120_235038_s1.IsoSeqX_bc04_5p--IsoSeqX_3p.flnc.bam
reference_genome: /gscratch/stergachislab/assemblies/simple-names/hg38.fa
pigeon_annot: /gscratch/stergachislab/asedeno/data/reference_files/gencode.v46.annotation.gtf
threads: 40