individuals:
  UDN318336:
    deepvariant_vcf: /gscratch/stergachislab/asedeno/data/Hank_MASseq/test_samples/UDN318336.vcf.gz
    untreated:
      non-cyclo_PS00449: 
        - /gscratch/stergachislab/asedeno/data/Hank_MASseq/test_samples/PS00449.unaligned.chr20.bam
    treated:
      cyclo_PS00450:
        - /gscratch/stergachislab/asedeno/data/Hank_MASseq/test_samples/PS00450.unaligned.chr20.bam
  UDN374570:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00459/hg38/results/pipelines/k-mer-variant-phasing/results/PS00459/hiphase/PS00459.vcf.gz
    untreated:
      non-cyclo_PS00460:
        - /gscratch/stergachislab/asedeno/data/Hank_MASseq/test_samples/PS00460.unaligned.chr20.bam
    treated:
      cyclo_PS00461:
        - /gscratch/stergachislab/asedeno/data/Hank_MASseq/test_samples/PS00461.unaligned.chr20.bam
  UDN212054:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00465/hg38/results/pipelines/k-mer-variant-phasing/results/PS00465/hiphase/PS00465.vcf.gz
    untreated:
      non-cyclo_PS00466:
        - /gscratch/stergachislab/asedeno/data/Hank_MASseq/test_samples/PS00466.unaligned.chr20.bam
    treated:
      cyclo_PS00467:
        - /gscratch/stergachislab/asedeno/data/Hank_MASseq/test_samples/PS00467.unaligned.chr20.bam
  UDN178694:
    deepvariant_vcf:
    untreated:
      non-cyclo_PS00490:
        - /gscratch/stergachislab/asedeno/data/Hank_MASseq/test_samples/PS00490.unaligned.chr20.bam
    treated:  
      cyclo_PS00491:
        - /gscratch/stergachislab/asedeno/data/Hank_MASseq/test_samples/PS00491.unaligned.chr20.bam
reference_genome: /gscratch/stergachislab/assemblies/simple-names/hg38.fa
pigeon_annot: /gscratch/stergachislab/asedeno/data/reference_files/gencode.v46.annotation.gtf
threads: 40
