---
individuals:
  UDN633333:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00115/hg38/results/pipelines/k-mer-variant-phasing/results/PS00115/hiphase/PS00115.vcf.gz
    untreated:
      non-cyclo_PS00344:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00344/m84036_230518_222043_s4/IsoSeqX_bc09_5p--IsoSeqX_3p/PS00344.m84036_230518_222043_s4.IsoSeqX_bc09_5p--IsoSeqX_3p.flnc.bam
    treated:
      cyclo_PS00345:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00345/m84036_230519_205749_s1/IsoSeqX_bc10_5p--IsoSeqX_3p/PS00345.m84036_230519_205749_s1.IsoSeqX_bc10_5p--IsoSeqX_3p.flnc.bam
  BCH_2401-01:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00398/hg38/results/pipelines/k-mer-variant-phasing/results/PS00398/hiphase/PS00398.vcf.gz
    treated:
      cyclo_PS00399:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00399/m84046_240422_220151_s3/IsoSeqX_bc07_5p--IsoSeqX_3p/PS00399.m84046_240422_220151_s3.IsoSeqX_bc07_5p--IsoSeqX_3p.flnc.bam
    untreated:
      non-cyclo_PS00400:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00400/m84046_240422_220151_s3/IsoSeqX_bc08_5p--IsoSeqX_3p/PS00400.m84046_240422_220151_s3.IsoSeqX_bc08_5p--IsoSeqX_3p.flnc.bam
  BCH_0252-01:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00404/hg38/results/pipelines/k-mer-variant-phasing/results/PS00404/PS00404.haplotagged.vcf.gz
    treated:
      cyclo_PS00405:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00405/m84046_240324_145021_s1/IsoSeqX_bc11_5p--IsoSeqX_3p/PS00405.m84046_240324_145021_s1.IsoSeqX_bc11_5p--IsoSeqX_3p.flnc.bam
    untreated:
      non-cyclo_PS00406:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00406/m84046_240324_145021_s1/IsoSeqX_bc12_5p--IsoSeqX_3p/PS00406.m84046_240324_145021_s1.IsoSeqX_bc12_5p--IsoSeqX_3p.flnc.bam
  BCH_1199-01:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00422/hg38/results/pipelines/k-mer-variant-phasing/results/PS00422/PS00422.haplotagged.vcf.gz
    treated:
      cyclo_PS00423:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00423/m84046_240324_145021_s1/IsoSeqX_bc01_5p--IsoSeqX_3p/PS00423.m84046_240324_145021_s1.IsoSeqX_bc01_5p--IsoSeqX_3p.flnc.bam
    untreated:
      non-cyclo_PS00424:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00424/m84046_240324_145021_s1/IsoSeqX_bc02_5p--IsoSeqX_3p/PS00424.m84046_240324_145021_s1.IsoSeqX_bc02_5p--IsoSeqX_3p.flnc.bam
  BCH_1986-01:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00425/hg38/results/pipelines/k-mer-variant-phasing/results/PS00425/hiphase/PS00425.vcf.gz
    treated:
      cyclo_PS00426:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00426/m84046_240324_145021_s1/IsoSeqX_bc03_5p--IsoSeqX_3p/PS00426.m84046_240324_145021_s1.IsoSeqX_bc03_5p--IsoSeqX_3p.flnc.bam
    untreated:
      non-cyclo_PS00427:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00427/m84046_240324_145021_s1/IsoSeqX_bc04_5p--IsoSeqX_3p/PS00427.m84046_240324_145021_s1.IsoSeqX_bc04_5p--IsoSeqX_3p.flnc.bam
  UDN052264:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00456/hg38/results/pipelines/k-mer-variant-phasing/results/PS00456/PS00456.haplotagged.vcf.gz
    untreated:
      non-cyclo_PS00366:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00366/m84046_230829_213454_s3/MAS_3p--10X_IsoSeqX_bc16_5p/PS00366.m84046_230829_213454_s3.MAS_3p--10X_IsoSeqX_bc16_5p.flnc.bam
    treated:
      cyclo_PS00367:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00367/m84046_230829_213454_s3/MAS_3p--10X_IsoSeqX_bc17_5p/PS00367.m84046_230829_213454_s3.MAS_3p--10X_IsoSeqX_bc17_5p.flnc.bam
  UDN374570:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00459/hg38/results/pipelines/k-mer-variant-phasing/results/PS00459/PS00459.haplotagged.vcf.gz
    untreated:
      non-cyclo_PS00460:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00460/m84046_240509_062343_s4/IsoSeqX_bc02_5p--IsoSeqX_3p/PS00460.m84046_240509_062343_s4.IsoSeqX_bc02_5p--IsoSeqX_3p.flnc.bam
    treated:
      cyclo_PS00461:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00461/m84046_240509_062343_s4/IsoSeqX_bc07_5p--IsoSeqX_3p/PS00461.m84046_240509_062343_s4.IsoSeqX_bc07_5p--IsoSeqX_3p.flnc.bam
  UDN212054:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00465/hg38/results/pipelines/k-mer-variant-phasing/results/PS00465/PS00465.haplotagged.vcf.gz
    untreated:
      non-cyclo_PS00362:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00362/m84046_230829_213454_s3/MAS_3p--10X_IsoSeqX_bc03_5p/PS00362.m84046_230829_213454_s3.MAS_3p--10X_IsoSeqX_bc03_5p.flnc.bam
    treated:
      cyclo_PS00363:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00363/m84046_230829_213454_s3/MAS_3p--10X_IsoSeqX_bc04_5p/PS00363.m84046_230829_213454_s3.MAS_3p--10X_IsoSeqX_bc04_5p.flnc.bam
  UDN687128:
    deepvariant_vcf: /mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS00468/hg38/results/pipelines/k-mer-variant-phasing/results/PS00468/PS00468.haplotagged.vcf.gz
    untreated:
      non-cyclo_PS00469:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00469/m84046_240509_062343_s4/IsoSeqX_bc09_5p--IsoSeqX_3p/PS00469.m84046_240509_062343_s4.IsoSeqX_bc09_5p--IsoSeqX_3p.flnc.bam
    treated:
      cyclo_PS00470:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00470/m84046_240509_062343_s4/IsoSeqX_bc01_5p--IsoSeqX_3p/PS00470.m84046_240509_062343_s4.IsoSeqX_bc01_5p--IsoSeqX_3p.flnc.bam
  UDN318336:
    deepvariant_vcf: /gscratch/stergachislab/asedeno/data/Hank_MASseq/4-deepvariant/UDN318336.vcf
    untreated:
      non-cyclo_PS00449:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00449/m84046_240329_064709_s2/IsoSeqX_bc11_5p--IsoSeqX_3p/PS00449.m84046_240329_064709_s2.IsoSeqX_bc11_5p--IsoSeqX_3p.flnc.bam
    treated:
      cyclo_PS00450:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00450/m84046_240329_064709_s2/IsoSeqX_bc12_5p--IsoSeqX_3p/PS00450.m84046_240329_064709_s2.IsoSeqX_bc12_5p--IsoSeqX_3p.flnc.bam
  UDN215640:
    deepvariant_vcf: null
    untreated:
      non-cyclo_PS00364:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00364/m84046_230829_213454_s3/MAS_3p--10X_IsoSeqX_bc08_5p/PS00364.m84046_230829_213454_s3.MAS_3p--10X_IsoSeqX_bc08_5p.flnc.bam
    treated:
      cyclo_PS00365:
        - /mmfs1/gscratch/stergachislab/data-store/PacBio-Kinnex/PS00365/m84046_230829_213454_s3/MAS_3p--10X_IsoSeqX_bc09_5p/PS00365.m84046_230829_213454_s3.MAS_3p--10X_IsoSeqX_bc09_5p.flnc.bam

reference_genome: /gscratch/stergachislab/assemblies/simple-names/hg38.fa
pigeon_annot: /gscratch/stergachislab/asedeno/data/reference_files/gencode.v47.annotation.gtf
docs_dir: /mmfs1/gscratch/stergachislab/asedeno/data/github/IsoSeq_smk/docs
threads: 8
max_reads: 90000000
downsample_reads: 90000000
