conda-frontend: "conda"
conda-use-mamba: false
rerun-incomplete: True
show-failed-logs: True
rerun-triggers: mtime
restart-times: 1
software-deployment-method:
  - conda
printshellcmds: True
cores: 32
local-cores: 4
