executor: slurm
jobs: 500
latency-wait: 60
max-jobs-per-second: 50
default-resources:
  - disk_mb=4096
  - mem_mb=80000
  - runtime=400
  - slurm_partition=ckpt
  - slurm_account=stergachislab
use-conda: true
conda-frontend: conda
rerun-incomplete: true
keep-going: true
set-resources:
  cluster:
    slurm_partition: "cpu-g2"
  create_dictionary:
    slurm_partition: "cpu-g2"
  add_tags_to_bam:
    slurm_partition: "cpu-g2"
  isoranker_analysis:
    slurm_partition: "cpu-g2"
