executor: slurm
jobs: 50
latency-wait: 60
max-jobs-per-second: 5
default-resources:
  - disk_mb=8096
  - mem_mb=10000
  - runtime=1200
  - slurm_partition=cpu-g2
  - slurm_account=stergachislab
use-conda: true
conda-frontend: conda
rerun-incomplete: true
keep-going: true
set-resources:
  cluster:
    slurm_partition: "cpu-g2"
  create_dictionary:
    slurm_partition: "cpu-g2"
  add_tags_to_bam:
    slurm_partition: "cpu-g2"
  isoranker_analysis:
    slurm_partition: "cpu-g2"

