name: Lint & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install black flake8

      # Optional: Display version info
      - name: Show tool versions
        run: |
          black --version
          flake8 --version

      # Use a config file for line length if present, fallback to --line-length=79
      - name: Run Black (code formatter)
        run: black --check . --line-length 79

      - name: Run flake8 (linter)
        run: flake8 . --max-line-length=79
