
name: IsoSeq Snakemake Workflow

on: [push, pull_request]

jobs:
  snakemake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install snakemake snakemake-executor-slurm

    - name: Execute Snakemake
      run: |
        snakemake --profile profiles/slurm-executor/ --configfile config/config.yaml -p -k

    - name: Generate HTML report
      run: |
        snakemake --report report.html

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        destination_dir: docs
        publish_branch: gh-pages
